### ISSUE TITLE
Grammarly doesn't work properly in the API editor

### ISSUE THREAD

**Issue by Nazarah** [apinf/openapi-designer#113]
# steps to reproduce
1. go to http://apinf.org/open-api-designer
2. click on a section where a new element can be added (e.g. path, tag)
3. start filling up the fields one by one.

# Result:
on clicking fields, all Document section links (e.g. Details, MIME types, etc.) get disappeared.
Page needs to be reloaded for the links to reappear.
This happens with all the sections where a new element can be added
![openapisections](https://cloud.githubusercontent.com/assets/17976243/26546287/ea758bd4-4471-11e7-8ef0-884bb86b190d.gif)

# System Info
Windows 8
Google chrome

**Comment by xylix** [comment]
Could not reproduce on Google Chrome 58 or Mozilla Firefox 54.

Could you test with browser extensions disabled?

**Comment by Nazarah** [comment]
@xylix I retested with disabling the browser extensions and updating the chrome browser. The bug could not been produced.
However, as soon as I enabled the browser extensions, the bug reappeared.
This should not be the case that in order for the GUI to work properly, user needs to disable all his browser extensions.
That is a serious usability issue.

**Comment by tulir** [comment]
It seems like you have some specific extension that breaks the UI. The UI works just fine for us with many common extensions enabled (e.g. uBlock Origin). Could you post a list of the extensions you're using or (preferably) try to narrow down the problem to a specific extension and post that one?

**Comment by Nazarah** [comment]
Here is the list of extensions running in my chrome browser:
Adblock
appear.in screen sharing
Application Launcher for Drive (by Google)
Avast Online Security
Google Docs
Google Docs Offline
Google Hangouts
Grammarly for Chrome
Jitsi Desktop Streamer
Postman
RSS Feed Reader
Skype Calling
The Great Suspender
Vysor

**Comment by tulir** [comment]
It seems that Grammarly messes with the page and makes some incorrect assumptions about the styling of textareas.

**Comment by Nazarah** [comment]
Grammerly is just an add on to see if the texts you are writing in website are correct in spelling and they are following a correct grammatical syntax. Should we go with the favor that we don't need to consider this add on? perhaps add a info text that the OpenAPi designer may not support all add-ons in the browsers?
