### ISSUE TITLE
Make sure Swagger output is valid

### ISSUE THREAD

**Issue by tulir** [apinf/openapi-designer#121]
Once #110 is merged and #75 is fixed, we should make sure that it is possible to create a valid Swagger file with the editor (i.e. if the input is valid, the output should be valid).

**Comment by xylix** [comment]
I have been testing the editor by hand after the recent PR:s as we are getting closer to milestone 1.0.0, and making issues for invalid output. I also researched automated input/output testing and came to the conclusion that it should be implemented when we start implementing other tests too.

Let's test the editor and close this issue once all changes for 1.0.0 have been merged.
