### ISSUE TITLE
Create about page content

### ISSUE THREAD

**Issue by xylix** [apinf/openapi-designer#175]
The about page doesn't currently exist. It should be created and relevant content should be added. Wireframe for the about page was created for #40. It looks like this ![aboutpage](https://cloud.githubusercontent.com/assets/17976243/26405167/29721632-409d-11e7-80e2-af1698f4170d.png)

**Comment by bajiat** [comment]
Here is a suggestion for About page content from @bajiat and @Nazarah 

# What is OpenAPI designer?

OpenAPI designer allows you to create and update  API design files. It is a a form based editor for designing APIs. It supports the OpenAPI/Swagger version 2.0. 

# Why use OpenAPI designer?

Developers can get started more easily if they can view an API design document and can try out the API calls.
API designers can share the design file and get feedback from other stakeholders. This facilitates collaborative API design process.
Coding skills and understanding of json/yaml is not required for using the OpenAPI designer. 
The UI guides the user through the process of creating the required information.

# How to use it?

When the editor is opened, there is an empty form. The design file can be created by adding paths, operations and parameters.
Definitions and Tags can be designed globally and referred in Paths, Operations, Parameters and Responses.
You can download the designed file as json or yaml format. The downloaded file can be viewed in Swagger / OpenAPI designer UI.

Future enhancements include uploading a pre-existing design file or modifications and saving the design file on server. OpenAPI version 3.0 support is also on the roadmap.

# More information

Visit the [project repository](https://github.com/apinf/openapi-designer) in Github
