### ISSUE TITLE
Update repo settings for openapi.design

### ISSUE THREAD

**Issue by tulir** [apinf/openapi-designer#190]
* [x] A webhook for automatic branch deployment to dev.openapi.design needs to be set up
* [x] Rename repository to openapi-designer
* [x] The URL in the project info should be changed to https://openapi.design ![project info](https://img.mau.lu/P46kn.png)

**Comment by brylie** [comment]
What are the webhook deployment steps?

**Comment by tulir** [comment]
Payload URL: https://dev.openapi.design/webhook
Content type: `application/json`
Events: `push` only

Generate a random string (~20 characters is probably good) for the secret and send it to me in a non-public way.

The webhook should probably remain inactive until @ccsr sets up the dev.openapi.design subdomain.

**Comment by tulir** [comment]
We should also rename the repository to openapi-design and change the info text to match ("OpenAPI" instead of "Open API")

**Comment by brylie** [comment]
I changed the repo name.

**Comment by tulir** [comment]
We now have the subdomain, so the webhook can be set up.

**Comment by brylie** [comment]
What service will listen for the webhook on the dev.openapi.design server? What is the endpoint the webhook should call?

![screenshot_20170627_100824](https://user-images.githubusercontent.com/17307/27574859-91eed28e-5b20-11e7-9580-890be582f2e5.png)

We can discuss this further in chat, after reading through the [webhooks documentation](https://developer.github.com/webhooks/).

**Comment by tulir** [comment]
See my comment above

> Payload URL: https://dev.openapi.design/webhook
Content type: application/json
Events: push only

> Generate a random string (~20 characters is probably good) for the secret and send it to me in a non-public way.

**Comment by brylie** [comment]
Cool. Enabled.

**Comment by tulir** [comment]
Branches are now automatically deployed to `https://dev.openapi.design/<branch>`
