### ISSUE TITLE
Remove semicolons

### ISSUE THREAD

**Issue by tulir** [apinf/openapi-designer#217]
[Semicolons](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) [are](http://inimino.org/~inimino/blog/javascript_semicolons) [useless](https://www.youtube.com/watch?v=gsfbh17Ax9I). Automatic semicolon insertion will happen regardless of whether or not semicolons are used. For the cases where ASI actually doesn't work, we can just use the [no-unexpected-multiline](http://eslint.org/docs/rules/no-unexpected-multiline) rule in ESLint.

**Comment by xylix** [comment]
@brylie Any input on this?

**Comment by brylie** [comment]
Even though they are optional, I think we should use them:

- [Do you recommend using semicolons after every statement in JavaScript?](https://stackoverflow.com/a/444082/1191545)

**Comment by tulir** [comment]
The problem in the answer below the one you linked is avoided as long as we use [no-unexpected-multiline](http://eslint.org/docs/rules/no-unexpected-multiline) in ESLint. Also, the cases where that rule is needed are very rare.

**Comment by brylie** [comment]
The follow up comments tend to agree to use semicolons, mainly for the reason of consistency:

> If a language has certain cases where a semi-colon is required, I would take that and apply it to all cases if possible simply for the sake of code that is easier to read and code that simply looks good
>
> -- Dalin Seivewright
---

> For the sake of consistency and future readability, include semicolons after every statement.
>
> -- JustinT
---
> Why hope that the JS interpreter will correctly guess your intentions (not just now, but with minor code changes) when you can just add the semicolon and communicate them unambiguously?
>
> - Andrzej Doyle

The linked article, [Semicolons in JavaScript are optional](https://mislav.net/2010/05/semicolons/),  also mentions cases where semicolons are useful.

I am just recommending we avoid the ambiguity here altogether, and use semi-colons.

**Comment by xylix** [comment]
Let's just keep the semicolons.
