### ISSUE TITLE
Dropdowns broken on IE

### ISSUE THREAD

**Issue by xylix** [apinf/openapi-designer#226]
<img width="380" alt="screen shot 2017-06-30 at 11 26 56" src="https://user-images.githubusercontent.com/13387304/27727430-1cfcabc2-5d87-11e7-82c3-2f18f30d6ef3.png">

Dropdowns in typefields work, but other dropdowns don't.

**Comment by tulir** [comment]
It seems that `Optionfield` conditions cause this.
