### ISSUE TITLE
Language selector wrong color on IE

### ISSUE THREAD

**Issue by xylix** [apinf/openapi-designer#263]
<img width="107" alt="screen shot 2017-07-08 at 12 05 45" src="https://user-images.githubusercontent.com/13387304/27984117-d68f56e4-63d5-11e7-95cd-ac125f2d9dd9.png">
<img width="122" alt="screen shot 2017-07-08 at 12 05 52" src="https://user-images.githubusercontent.com/13387304/27984118-d68fb468-63d5-11e7-8e6c-987e7df67898.png">

**Comment by tulir** [comment]
It most likely isn't actually broken, just incorrectly colored.
