### ISSUE TITLE
Indicate user login status and allow logout

### ISSUE THREAD

**Issue by tulir** [apinf/openapi-designer#309]

**Comment by tulir** [comment]
We need to wait for decisions on #325 before continuing with further Space work.

**Comment by Nazarah** [comment]
Are we talking about registered users from APInf or separate users using OpenAPI Designer as an independent service?

**Comment by xylix** [comment]
@Nazarah Both. From the view of the backend both are users of OpenAPI space.

**Comment by JeHugawa** [comment]
Logout is allready implemented however login status is a good low hanging fruit.
