### ISSUE TITLE
Tab: Header: sign i permanently visible on page

### ISSUE THREAD

**Issue by matleppa** [apinf/openapi-designer#316]
Host settings > Base path
i sign permanently visible.
![header_page.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46e0919b278791969fe8b846e611b2843b492d762a10e17132d0bb7aba4028530c5b4bae145f5f15fbf9897ea4b26d708d4e17ff933c0120996048e6edc00db513b826814e80b6bc8f49c5e93a2def83875d73.PNG)

**Comment by xylix** [comment]
It is an info sign so it is supposed to be visible. Does it look too much like the error signs?

**Comment by matleppa** [comment]
OK. On the other hand it looks like error sign, but on the other hand the functionality is similar: more info. 
I guess the color is enough to to separate info from error.
