### ISSUE TITLE
Tab: MIME Types list items modifiable

### ISSUE THREAD

**Issue by matleppa** [apinf/openapi-designer#320]
It should not be possible to enter input fields for consumes and produces other values than the ones in drop-down lists.
Now the selected values can be altered or completely other values can be given.

On the other hand, I'm wondering to the selection 
text/plain; charset=utf-8
Is it easier to let user alter the charset, if needed, instead of offering all alternatives?

Does it lead to too complicated implementation, if other selections are not 
possible to modify by user, but the one with charset is?

**Comment by tulir** [comment]
There are a lot of different MIME types, so we can't really add all them as options and we don't want to restrict the user to the ones we could think about. After all, an API can return pretty much anything, videos, binary data, documents, JSON, images, text, etc..

**Comment by matleppa** [comment]
OK, no changes needed here.
