### ISSUE TITLE
Remove upload system modularity

### ISSUE THREAD

**Issue by tulir** [apinf/openapi-designer#325]
It's not really that modular and we probably don't need it to be modular: there aren't any other systems we really need to support. A Space-only upload system would also allow for a more Space-focused UI.

If we do really want the modularity, we should probably open a new issue to make the upload system actually modular (supporting custom authentication, other actions like publishing, etc) rather than just having a slightly easier way to add buttons to the upload dropdown menu.

**Comment by xylix** [comment]
@ccsr @brylie @bajiat Any input on this?

**Comment by brylie** [comment]
It is fine to focus the project more narrowly.

**Comment by bajiat** [comment]
This approach for narrowing it to Space seems appropriate to me.
