### ISSUE TITLE
Review finnish localisation texts

### ISSUE THREAD

**Issue by xylix** [apinf/openapi-designer#335]
@xylix Where can I find the translations? In which file?

**Comment by JeHugawa** [comment]
There was few untranslated lines in openapi-designer/src/lang/fi.json, and there is no translation for <a href="https://openapi.design/#/about"> about section</a> .

**Comment by xylix** [comment]
@baijat Finnish translations are located here https://github.com/apinf/openapi-designer/blob/master/src/lang/fi.json .
