### ISSUE TITLE
Consider blending form-based designer with rich preview

### ISSUE THREAD

**Issue by brylie** [apinf/openapi-designer#4]
# Open API Designer
We are currently building a simple **form-based design** tool, with **code preview** on the right. 
![screenshot_20161108_105113](https://cloud.githubusercontent.com/assets/17307/20092673/11a426a8-a5a2-11e6-8e65-13087276aef6.png)

# Swagger Editor
The [Swagger Editor](http://editor.swagger.io/#/) project has a **code editor** on the left with a **rich preview** on the right.
![screenshot_20161108_104911](https://cloud.githubusercontent.com/assets/17307/20092699/2aecfd7e-a5a2-11e6-8646-a65a70babee2.png)

# Hybrid approach?
What are some thoughts and considerations about possibly combining the **form-based designer** with the **rich preview**, for a best of both worlds?

![openapidesigner-swaggereditor-hybrid](https://cloud.githubusercontent.com/assets/17307/20263415/42b5f592-aa6f-11e6-9aab-96686e7fc46b.png)

**Comment by bajiat** [comment]
Would it make sense to give users an option to toggle between json preview and rich preview?

The form field on the left could be divided into sections, since the page is getting really long.

**Comment by brylie** [comment]
> The form field on the left could be divided into sections, since the page is getting really long.

@bajiat, lets open that as a separate issue.

**Comment by tulir** [comment]
I added a tab for rich preview in 0e4fad3, but actually producing a rich preview isn't implemented. I tried to use [swagger-ui](https://github.com/swagger-api/swagger-ui), but couldn't get it to work yet.

**Comment by brylie** [comment]
@tulir lets focus on the main schema fields for now. This issue is mainly for discussion.

**Comment by kyyberi** [comment]
+1
