### ISSUE TITLE
Consider collaboration with OpenAPI GUI project

### ISSUE THREAD

**Issue by brylie** [apinf/openapi-designer#85]
While browsing our stargazers, I noticed that @MikeRalphson is maintaining a project called [OpenAPI GUI](https://github.com/Mermade/openapi-gui). How might we partner with that developer/project, so our efforts are mutually beneficial?

cc: @bajiat @tulir @Nazarah @xylix

**Comment by MikeRalphson** [comment]
Thanks for reaching out! It would be awesome to cross-polinate ideas, especially if you're planning to support OpenAPI 3.0.x. The latest visual refresh of the project is in the [buefy](https://github.com/mermade/openapi-gui/tree/buefy) branch and there is a [live demo](http://openapi-gui.herokuapp.com/).

**Comment by MikeRalphson** [comment]
I'm interested in your persistence layer, will it be hosted with an open API or for local deployments only? I'm planning at some stage to add pluggable storage backends, i.e. the existing localStorage one, and  integration with the [SwaggerHub API](http://swagger.io/integrating-with-the-swaggerhub-api/). We could collaborate on a compatible DB schema and/or a standard for localStorage and IndexedDB usage?

One thing I have noticed about your project is your visual design follows the the structure of the OpenAPI specification very closely. I feel that has benefits for people familiar with the specification but it might also limit your UX choices, i.e. the UI does not necessarily need to expose all of the aspects of the specification (such as parameters being held at three levels - this could be handled by automatic placement of parameters when they are created/copied/modified, or by a post-processing step before the API definition is saved).

**Comment by brylie** [comment]
@MikeRalphson, @JeHugawa, and @xylix, should we discuss the persistence layer in the [related issue](https://github.com/apinf/open-api-designer/issues/70)?

**Comment by brylie** [comment]
> One thing I have noticed about your project is your visual design follows the structure of the OpenAPI specification very closely. I feel that has benefits for people familiar with the specification but it might also limit your UX choices

@MikeRalphson, great point! Would you consider adding that feedback to issue #40? We are actively wireframing some ideas for the UI, and would appreciate your perspective.

**Comment by ccsr** [comment]
I give my input strategically from APInf point of view. 
1. We started this project because some customers requested us. So we need to host this anyway to be able to work with APInf. Also we would be happy to allow collaborators also to use our backend or integrate. @MikeRalphson so the idea of reusing the backend is a great.
2. We would like to provide this tool through APInf for all APInf users for free. Also host the specifications & also listing API in catalogue for free. This way it is beneficial for all collaborators, customers, developers and APInf.

**Comment by MikeRalphson** [comment]
http://www.apicur.io/ also seems to be worth looking at.

**Comment by tulir** [comment]
Discussion has moved to other issues and the openapi-space repository, so I'll close this issue.
