### ISSUE TITLE
Split-GUI in OpenAPI Designer

### ISSUE THREAD

**Issue by Nazarah** [apinf/openapi-designer#92]
# User Story
In online editors like SwaggerHub, users can change between Swagger UI, Editor or a Split screen to view the previous two elements in the same time. 
Also the split view can be customized to change the width of the UI/Editor window
This gives users flexibility to view what is more important to them.
> "As an OpenAPI designer, I want to have a split UI option so that I can switch between editor, UI or a combination of both."
![splitgui](https://cloud.githubusercontent.com/assets/17976243/26244067/f1520e92-3c96-11e7-9178-13c86ca5b1f3.gif)

**Comment by Nazarah** [comment]
Related to #92

**Comment by tulir** [comment]
Once we have this, we can add a lot of margin to the sides of the page.
