### ISSUE TITLE
Add i18n support for UI texts

### ISSUE THREAD

**Issue by Nazarah** [apinf/openapi-designer#99]
Add internationalization (i18n) support to the project, so that we can translate user interface texts. Once the i18n package is configured, determine how to follow-up with user interface internationalization, including the following
- menu texts
- form texts

# Definition of Done
TBD

# Resources
- [i18n with Aurelia](http://aurelia.io/hub.html#/doc/article/aurelia/i18n/latest/i18n-with-aurelia)

**Comment by brylie** [comment]
@Nazarah I added a description to this task.

**Comment by brylie** [comment]
I think we should add this i18n support for the 1.0 release. We can include Suomi localization as part of that release, or wait for 1.1.0 release. By the way, do we want to use semantic versioning starting at version 1.0?

**Comment by brylie** [comment]
The Aurelia i18n guide expects localizations to be served by a backend. That might be problematic, since this is a client-only project. Lets see if there is another way to provide the localizations, and consider the bundle size if they are included with the client code.

**Comment by brylie** [comment]
E.g. might we be able to host i18n files on a CDN or some dedicated location?

**Comment by xylix** [comment]
I think it's possible to load them from anywhere. [These](https://github.com/aurelia/i18n/blob/master/doc/article/en-US/i18n-with-aurelia.md) docs `backend: {                                  // <-- configure backend settings
          loadPath: './locales/{{lng}}/{{ns}}.json', // <-- XHR settings for where to get the files from
        },` make it look like the json for localization can be hosted anywhere.
